import { Transaction } from './transaction';
export declare class Block {
    static fromBuffer(buffer: Buffer): Block;
    static fromHex(hex: string): Block;
    static calculateTarget(bits: number): Buffer;
    static calculateMerkleRoot(transactions: Transaction[], forWitness?: boolean): Buffer;
    version: number;
    prevHash?: Buffer;
    merkleRoot?: Buffer;
    timestamp: number;
    witnessCommit?: Buffer;
    bits: number;
    nonce: number;
    transactions?: Transaction[];
    blockHeight: number;
    currentSignBlockScript?: Buffer;
    currentSignBlockWitnessLimit: number;
    currentElidedRoot?: Buffer;
    currentSignBlockScriptFull?: Buffer;
    currentSignBlockWitnessLimitFull: number;
    currentFedpegProgram?: Buffer;
    currentFedpegScript?: Buffer;
    currentExtensionSpace?: Buffer[];
    proposedSignBlockScript?: Buffer;
    proposedSignBlockWitnessLimit: number;
    proposedElidedRoot?: Buffer;
    proposedSignBlockScriptFull?: Buffer;
    proposedSignBlockWitnessLimitFull: number;
    proposedFedpegProgram?: Buffer;
    proposedFedpegScript?: Buffer;
    proposedExtensionSpace?: Buffer[];
    signBlockWitness?: Buffer[];
    challenge?: Buffer;
    solution?: Buffer;
    getWitnessCommit(): Buffer | null;
    hasWitnessCommit(): boolean;
    hasWitness(): boolean;
    weight(): number;
    byteLength(headersOnly?: boolean, allowWitness?: boolean): number;
    getHash(): Buffer;
    getId(): string;
    getUTCDate(): Date;
    toBuffer(headersOnly?: boolean): Buffer;
    toHex(headersOnly?: boolean): string;
    checkTxRoots(): boolean;
    checkProofOfWork(): boolean;
    private __checkMerkleRoot;
    private __checkWitnessCommit;
}
